
export default {
    MOVIES_GET_REQUEST  : 'MOVIES_GET_REQUEST',
    MOVIES_GET_SUCCESS  : 'MOVIES_GET_SUCCESS',
    MOVIES_GET_FAIL     : 'MOVIES_GET_FAIL',

    MOVIEDETAILS_GET_REQUEST  : 'MOVIEDETAILS_GET_REQUEST',
    MOVIEDETAILS_GET_SUCCESS  : 'MOVIEDETAILS_GET_SUCCESS',
    MOVIEDETAILS_GET_FAIL     : 'MOVIEDETAILS_GET_FAIL',

    ERROR_CLEAR : 'ERROR_CLEAR'
};
